In [33]:
# simplified attention 
# calculate the context vector for each element 


In [34]:
import torch 
inputs=torch.tensor([[ 0.1420, -0.6450, -1.9561],# Your 
        [ 0.6865, -0.8105,  0.1787],# Journey 
        [ 1.6777,  1.5439,  0.4634],# Starts
        [-0.5454, -1.4678,  0.5532],# with 
        [-0.8848,  0.4507, -0.4956],# one 
        [ 0.3020,  1.8945, -2.1953]])# step
# STEP 
# here these are vector embeddings fot respective words now we need to create a attention mechanism so that our RNN can understand which word is holding the semantic meaning of the

In [35]:
query=inputs[1]
attn_scores=torch.empty(inputs.shape[0])
for i , x_i in enumerate(inputs):
    attn_scores[i]=torch.dot(x_i,query)

print((attn_scores/sum(attn_scores))) 
print(sum(attn_scores))  # this is attention weights 

tensor([-0.5968, -2.5576,  0.0370, -2.0152,  2.3396,  3.7929])
tensor(-0.4536)


In [36]:
def softmax_naive(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)
print((softmax_naive(attn_scores)))# this is for journey 

tensor([0.1541, 0.3752, 0.1156, 0.2933, 0.0407, 0.0210])


In [37]:
def attention_matrix(inputs):
    attention_weights=[]
    for i in range(len(inputs)):
        querx=inputs[i]
        attn_scores=torch.empty(inputs.shape[0])
        for j , x_i in enumerate(inputs):
            attn_scores[j]=torch.dot(x_i,querx)
        _scores= softmax_naive(attn_scores/sum(attn_scores))
        attention_weights.append(_scores) 
    return attention_weights   


In [38]:
attention_matrix(inputs)

[tensor([0.2627, 0.1397, 0.1029, 0.1295, 0.1461, 0.2191]),
 tensor([0.0097, 0.0014, 0.0183, 0.0024, 0.1835, 0.7847]),
 tensor([0.0276, 0.0583, 0.6856, 0.0156, 0.0370, 0.1758]),
 tensor([0.1269, 0.0963, 0.2468, 0.0613, 0.1346, 0.3341]),
 tensor([0.1402, 0.0246, 0.0257, 0.0474, 0.2917, 0.4704]),
 tensor([0.1782, 0.1089, 0.1659, 0.0850, 0.1539, 0.3082])]

`[tensor([0.2627, 0.1397, 0.1029, 0.1295, 0.1461, 0.2191]),
 tensor([0.0097, 0.0014, 0.0183, 0.0024, 0.1835, 0.7847]),
 tensor([0.0276, 0.0583, 0.6856, 0.0156, 0.0370, 0.1758]),
 tensor([0.1269, 0.0963, 0.2468, 0.0613, 0.1346, 0.3341]),
 tensor([0.1402, 0.0246, 0.0257, 0.0474, 0.2917, 0.4704]),
 tensor([0.1782, 0.1089, 0.1659, 0.0850, 0.1539, 0.3082])] `

In [39]:
attn_weights=torch.softmax(inputs @ inputs.T,dim=-1)# this is attention 

In [40]:
attn_weights# simple attention

tensor([[7.2754e-01, 1.3435e-02, 1.9408e-03, 8.2840e-03, 1.7819e-02, 2.3098e-01],
        [1.5415e-01, 3.7515e-01, 1.1563e-01, 2.9333e-01, 4.0688e-02, 2.1047e-02],
        [7.9876e-04, 4.1477e-03, 9.4614e-01, 2.2640e-04, 1.5236e-03, 4.7164e-02],
        [4.0875e-02, 1.2615e-01, 2.7143e-03, 7.9733e-01, 3.2143e-02, 7.8934e-04],
        [1.4678e-01, 2.9212e-02, 3.0496e-02, 5.3662e-02, 2.8930e-01, 4.5055e-01],
        [4.5507e-03, 3.6140e-05, 2.2578e-03, 3.1518e-06, 1.0776e-03, 9.9207e-01]])

In [41]:
context_vec_all=attn_weights @ inputs

# Self attention 

In [42]:
input_embeding=torch.tensor([
  [ 0.5981,  0.3744,  0.1341],# Your 
  [ 0.0651, -0.7321,  0.0762],# Journey 
  [-0.1848,  0.7833,  0.8625],# Starts
  [-0.4904, -0.6280,  0.8228],# with 
  [-0.0195,  0.6838, -0.8091],# one 
  [-0.7579,  0.6604, -0.2468]# step 
])


In [43]:
# self attention : it allows model to assign the importance of the weights of the words simlulatenously for that there is three thing 
# query , key , value : these are weight matrix to create the attention 
torch.manual_seed(332)
w_query=torch.nn.Parameter(torch.rand(input_embeding.shape[1],2),requires_grad=True)
w_key=torch.nn.Parameter(torch.rand(input_embeding.shape[1],2),requires_grad=True)# these are weights 
w_value=torch.nn.Parameter(torch.rand(input_embeding.shape[1],2),requires_grad=True)

In [44]:
w_query,w_key,w_value

(Parameter containing:
 tensor([[0.0528, 0.0775],
         [0.4305, 0.1395],
         [0.0446, 0.5122]], requires_grad=True),
 Parameter containing:
 tensor([[0.0901, 0.2954],
         [0.6079, 0.4728],
         [0.9203, 0.7876]], requires_grad=True),
 Parameter containing:
 tensor([[0.0337, 0.0011],
         [0.9006, 0.6936],
         [0.7763, 0.8951]], requires_grad=True))

In [45]:
# so for individual thing we can do this 
for index, data in enumerate(input_embeding):# weight_query
    print(f"index {index}--> query weight {data @ w_query}")
# similary for key and value     vector formed 


index 0--> query weight tensor([0.1987, 0.1673], grad_fn=<SqueezeBackward4>)
index 1--> query weight tensor([-0.3083, -0.0581], grad_fn=<SqueezeBackward4>)
index 2--> query weight tensor([0.3659, 0.5368], grad_fn=<SqueezeBackward4>)
index 3--> query weight tensor([-0.2596,  0.2958], grad_fn=<SqueezeBackward4>)
index 4--> query weight tensor([ 0.2573, -0.3205], grad_fn=<SqueezeBackward4>)
index 5--> query weight tensor([ 0.2333, -0.0930], grad_fn=<SqueezeBackward4>)


In [46]:
input_query,input_key,input_value=input_embeding @ w_query,input_embeding @ w_key, input_embeding @ w_value

In [47]:
# consider we want to find the now there is example here query is just the vectorized version of the word consider for this here is journey 
journey=input_query[2]# vectorized form of journey so how the attention score
attn_scores_journey=journey @ input_key.T# this is specific for the data
attn_weights_journey=torch.softmax(attn_scores_journey/w_key.shape[-1]**0.5,dim=-1)
attn_scores_journey @input_value

tensor([1.7174, 1.7165], grad_fn=<SqueezeBackward4>)

In [48]:
attn_scores2=input_query @ input_key.T
# normalize the attention weights 
d_k=w_key.shape[1]
attn_weights_self=torch.softmax(attn_scores2/d_k**0.5,dim=-1)
attn_weights_self@input_value

tensor([[0.3497, 0.3318],
        [0.2043, 0.1850],
        [0.4635, 0.4453],
        [0.2708, 0.2529],
        [0.2757, 0.2566],
        [0.3100, 0.2915]], grad_fn=<MmBackward0>)

In [49]:
# now we will calculate the context vector 
import torch.nn as nn
class Self_attention(nn.Module):
    def __init__(self, input,dout):
        super().__init__()
        self.input =input
        # self.weights_query=nn.Parameter(torch.rand(input.shape[1],dout),requires_grad=True)
        # self.weights_key=nn.Parameter(torch.rand(input.shape[1],dout),requires_grad=True)
        # self.weights_value=nn.Parameter(torch.rand(input.shape[1],dout),requires_grad=True)
        self.weights_query=nn.Linear(input.shape[1],dout,bias=False)
        self.weights_key=nn.Linear(input.shape[1],dout,bias=False)
        self.weights_value=nn.Linear(input.shape[1],dout,bias=False)
        self.query=self.input@self.weights_query.weight.T
        self.keys=self.input@self.weights_key.weight.T
        self.value=self.input@self.weights_value.weight.T
        self.d_k=self.weights_key.weight.T.shape[1]
    def forward(self):
        self.attn_scores=self.query@self.keys.T
        self._attn_weights= torch.softmax(self.attn_scores/self.d_k**0.5,dim=-1)
        self.context_vector = self._attn_weights @ self.value
        return self.context_vector
 # here  in this version of code there is a catch for intializing the weights right now we are using the random numbers but it can further do more effiecently via intilising the linear        

In [50]:
sa=Self_attention(input_embeding,2)
sa.forward()# this is contex vector for each word 
# sa._attn_weights

tensor([[-0.1221, -0.0181],
        [-0.1236,  0.0286],
        [-0.1187, -0.1267],
        [-0.1205, -0.0763],
        [-0.1273,  0.1141],
        [-0.1283,  0.0510]], grad_fn=<MmBackward0>)

# causal attention 

In [51]:
batches=torch.stack((input_embeding,input_embeding))

In [52]:
# this is called the masked attention 
class Causal_attention(nn.Module):
    def __init__(self, numemb,dout,drop_out=0.2,context_length=int):
        super().__init__()
        self.input =numemb
        self.dropout_rate=drop_out
        self.context_length=context_length
        # self.weights_query=nn.Parameter(torch.rand(input.shape[1],dout),requires_grad=True)
        # self.weights_key=nn.Parameter(torch.rand(input.shape[1],dout),requires_grad=True)
        # self.weights_value=nn.Parameter(torch.rand(input.shape[1],dout),requires_grad=True)
        self.weights_query=nn.Linear(self.input,dout,bias=False)
        self.weights_key=nn.Linear(self.input,dout,bias=False)
        self.weights_value=nn.Linear(self.input,dout,bias=False)
        self.d_k=self.weights_key.weight.T.shape[1]
        self.dropout=None
    def forward(self,inputs):# we can handle the data in batches 
        self.query=self.weights_query(inputs)
        self.keys=self.weights_key(inputs)
        self.value=self.weights_value(inputs)
        try:
           self.attn_scores=self.query@self.keys.transpose(1,2)
        except Exception as e :
            self.attn_scores=self.query@self.keys.T
        self.masked=torch.triu(self.attn_scores,diagonal=1)
        self.dropout=nn.Dropout(self.dropout_rate)
        self.casual_attn_scores=self.attn_scores.masked_fill(self.masked.bool()[:self.context_length,:self.context_length],-torch.inf)
        self.cas_attn_weights= torch.softmax(self.casual_attn_scores/self.d_k**0.5,dim=-1)# here 
        # normalising again 
        self.normalised_causal_attn=self.dropout(self.cas_attn_weights)
        return self.normalised_causal_attn @ self.keys
    # in this approach there is problem problem is that we are sharing the weights infulence via softmaxing the attn scores 
    # so this creates a data leakage problem in it : where as causal attention strictly dont allow to access the fututre tokens 
        
        
       
    

In [53]:
batches.shape

torch.Size([2, 6, 3])

In [54]:
emb=batches.shape[2]
casual_attention=Causal_attention(emb,2,context_length=batches.shape[1])
casual_attention.forward(batches)


tensor([[[-0.3247, -0.1328],
         [ 0.0095, -0.0015],
         [-0.1095, -0.1938],
         [-0.1299, -0.1499],
         [-0.0609, -0.1800],
         [-0.0412, -0.0292]],

        [[-0.3247, -0.1328],
         [ 0.0095, -0.0015],
         [-0.2158, -0.2373],
         [-0.0775, -0.2227],
         [ 0.0181, -0.0088],
         [-0.1868, -0.0821]]], grad_fn=<UnsafeViewBackward0>)

# multi head attention 

In [55]:
# the idea is that the we can run the causal attention in parallel so that it can find complex pattern for words 

class Multi_Head_Wrapper(nn.Module):
    def __init__(self,din,dout,drop_out=0.2,num_heads=3,context_length=int):
        super().__init__()
        self.din=din
        self.dout=dout
        self.drop_=drop_out
        self.num_h=num_heads
        self.context_length=context_length
    def forward(self,x):
        self.head_cv=[]
        for i in range(self.num_h):
            self.context_vector=Causal_attention(self.din,self.dout,self.drop_,self.context_length).forward(x)
            self.head_cv.append(self.context_vector)
        return torch.cat(self.head_cv,dim=-1)

In [ ]:
batches.shape
# here 2 is batch size 
# 6 is the number of tokens 
# 3 is the vector embedding of these three tokens 


torch.Size([2, 6, 3])

In [88]:
input_embeding.transpose_(2,2)

tensor([[[ 0.5981,  0.0651, -0.1848, -0.4904, -0.0195, -0.7579],
         [ 0.3744, -0.7321,  0.7833, -0.6280,  0.6838,  0.6604],
         [ 0.1341,  0.0762,  0.8625,  0.8228, -0.8091, -0.2468]]])

In [ ]:

mtl=Multi_Head_Wrapper(3,2,num_heads=2,context_length=batches.shape[1])
values=mtl.forward(batches)


tensor([[[ 0.0536, -0.1063,  0.0699, -0.2649],
         [-0.1658,  0.1310, -0.1690, -0.1078],
         [-0.1163,  0.0944,  0.1788,  0.0024],
         [-0.1797,  0.3277,  0.0146,  0.1983],
         [-0.0392,  0.2561,  0.0444,  0.0899],
         [ 0.1302, -0.0060,  0.1094,  0.0739]],

        [[ 0.0536, -0.1063,  0.0699, -0.2649],
         [-0.1658,  0.1310, -0.1690, -0.1078],
         [-0.1163,  0.0944, -0.0106,  0.1111],
         [-0.0252,  0.1360,  0.0636,  0.0400],
         [-0.0283,  0.2344,  0.0166,  0.0051],
         [ 0.1762, -0.1381,  0.0332,  0.0313]]], grad_fn=<CatBackward0>)

In [ ]:
class Multi_Head_Attention(nn.Module):
    def __init__(self,din_,dout,dropout_r,numh,bias=False):
        super().__init__()
        self.dout=dout
        self.heads=numh
        self.head_dim=self.dout//self.heads
        self.w_query=nn.Linear(din_,dout,bias=bias)
        self.w_key=nn.Linear(din_,dout,bias=bias)
        self.w_value=nn.Linear(din_,dout,bias=bias)
        self.out_proj=nn.Linear(dout,dout)
        self.dropout=nn.Dropout(dropout_r)
    def forward(self,x):
        batch,num_tokens,din_emb=x.shape
        query=self.w_query(x)
        key= self.w_key(x)
        value=self.w_value(x)
        key=key.view(batch,num_tokens,self.heads,self.head_dim)
        query=query.view(batch,num_tokens,self.heads,self.head_dim)
        value=value.view(batch,num_tokens,self.heads,self.head_dim)
        key=key.transpose(1,2)
        query=query.transpose(1,2)
        value=value.transpose(1,2)
        self.attn_scores=query @ key.transpose(2,3)
        masked=torch.triu(self.attn_scores,diagonal=1)
        attn_scoresx=self.attn_scores.masked_fill(masked.bool()[:num_tokens,:num_tokens],-torch.inf)
        attn_weight=torch.softmax(attn_scoresx/key.shape[-1],dim=-1)
        self.final_weights=self.dropout(attn_weight)
        self.context_vec=(self.final_weights @ value).transpose(1,2)
        self.context_vec_f=self.context_vec.contiguous().view(batch,num_tokens,self.dout)
        self.context_vec_f=self.out_proj(self.context_vec_f)
        return self.context_vec_f
    

In [97]:
batch,num_tokens,din_=batches.shape
'''
There are  Three things to say first is 2--> is the batch size 
6--> no. of tokens
3--> embedding shape of token 
'''
multi_head_attention=Multi_Head_Attention(din_,6,0.0,numh=2)
print(multi_head_attention.forward(batches).shape)
print(multi_head_attention.forward(batches))


# the here is your context_vector  bitch !

torch.Size([2, 6, 6])
tensor([[[ 0.4454, -0.2872, -0.3774, -0.0540, -0.0765, -0.1879],
         [ 0.3945, -0.2814, -0.3125, -0.1696, -0.0066, -0.1245],
         [ 0.4396, -0.2310, -0.3267, -0.0765, -0.0693, -0.2311],
         [ 0.4438, -0.2033, -0.2882, -0.0909, -0.0622, -0.2455],
         [ 0.3993, -0.2137, -0.2971, -0.1354, -0.0294, -0.2111],
         [ 0.3740, -0.2077, -0.3073, -0.1487, -0.0209, -0.2153]],

        [[ 0.4454, -0.2872, -0.3774, -0.0540, -0.0765, -0.1879],
         [ 0.3945, -0.2814, -0.3125, -0.1696, -0.0066, -0.1245],
         [ 0.4396, -0.2310, -0.3267, -0.0765, -0.0693, -0.2311],
         [ 0.4438, -0.2033, -0.2882, -0.0909, -0.0622, -0.2455],
         [ 0.3993, -0.2137, -0.2971, -0.1354, -0.0294, -0.2111],
         [ 0.3740, -0.2077, -0.3073, -0.1487, -0.0209, -0.2153]]],
       grad_fn=<ViewBackward0>)
